version: "3.7"
services:
  backend:
    container_name: "perfume-house-backend"
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - .:/backend/app
    ports:
      - 3500:3000
      - 3501:3001
    networks:
      - perfume-house-network
  frontend:
    container_name: "perfume-house-frontend"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - .:/frontend/app
    ports:
      - 80:80
      - 443:443
    networks:
      - perfume-house-network
networks:
  perfume-house-network:
    name: perfume-house-internal
