name: Check code formatting when pull request any branch and push any branch except main

on:
  push:
    branches:
      - "*"
      - "!main"
  pull_request:
    branches:
      - "main"

jobs:
  check-code:
    name: Check code format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Check code format in backend
        working-directory: ./backend
        run: |
          yarn install
          yarn prettier-check
      - name: Check code format in frontend
        working-directory: ./frontend
        run: |
          yarn install
          yarn prettier-check
